repos:
  - repo: local
    hooks:
      - id: go-lint
        name: Go Lint
        entry: make lint
        language: system
        types: [go]
        pass_filenames: false

      - id: go-build
        name: Go Build
        entry: make build
        language: system
        types: [go]
        pass_filenames: false

      - id: go-test
        name: Go Test
        entry: make test
        language: system
        types: [go]
        pass_filenames: false
